# Generated by Django 3.0.2 on 2020-02-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ingresos'), (2, 'Gastos'), (3, 'Costos')], default=2),
        ),
    ]
