# Generated by Django 3.0.2 on 2020-02-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ingresos'), (2, 'Gastos administrativos'), (3, 'Gastos de ventas')], default=2),
        ),
    ]
